### ISSUE TITLE
It seems like transpilation is not working on .coffee files

### ISSUE THREAD

**Issue by robguthrie** [cxsper/vue-cli-plugin-coffee#2]
Hi, I depend on this plugin for our app, Loomio, and really appreciate it!

I've recently been trying to understand why IE11 does not work and it seems like there are lots of class keywords still in my compiled sources.

Everything in my vue.config.js tells me that class should be transpiled out but it does not seem to be happening.

My babel.config.js is
```
module.exports = {
  presets: [["@vue/app", { useBuiltIns: "entry" }]]
}
```

And my package.json has
```
  "browserslist": ["IE 11", "> 0.5%", "last 2 versions", "Firefox ESR", "not dead"],
```

I also have a minimal .babelrc as specified by https://coffeescript.org/#transpilation

But in my final legacy build source code I see stuff like this:

```
u=class{constructor({onProgress:e}){this.
```

Which IE dies on, and I think shouldn't be there if the code was transpiled.

Any ideas? I'm rather desperate! Thank you

**Comment by cxsper** [comment]
@robguthrie not sure it is caused by this plugin, because it is very simple and what it does is just adding proper loader here https://github.com/cxsper/vue-cli-plugin-coffee/blob/master/index.js 

Until loader is working correctly and your code is fine - it should be ok. This plugin doesn't provide any configuration for anything but it rather setting a loader for `.coffee` files. So please, try to find your problem elsewhere - in `.babelrc` or try to find issues here https://github.com/webpack-contrib/coffee-loader

Sorry for such long delay, haven't seen any notifications.

**Comment by robguthrie** [comment]
Hi @cxsper, thanks for getting back to me. I've just moved on, dropping support for those older browsers seems to be viable now, which is nice.
